//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public System.DateTime date { get; set; }
        public System.Guid id { get; set; }
        public string description { get; set; }
        public string patientusername { get; set; }
        public string medicusername { get; set; }
        public System.DateTime datecreated { get; set; }
        public string confirmed { get; set; }
    }
}
