//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nurse
    {
        public string forename { get; set; }
        public string lastname { get; set; }
        public string speciality { get; set; }
        public string username { get; set; }
        public System.Guid id { get; set; }
        public string accesstype { get; set; }
        public string phoneno { get; set; }
        public string email { get; set; }
    }
}
