//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public string forename { get; set; }
        public string secondname { get; set; }
        public string lastname { get; set; }
        public string familyname { get; set; }
        public string sex { get; set; }
        public string citizenship { get; set; }
        public string education { get; set; }
        public string pesel { get; set; }
        public string dateofbirth { get; set; }
        public string insuranceno { get; set; }
        public string email { get; set; }
        public string phoneno { get; set; }
        public string street { get; set; }
        public string housenumber { get; set; }
        public string local { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string datecreated { get; set; }
        public string username { get; set; }
        public string accesstype { get; set; }
        public System.Guid id { get; set; }
    }
}
